#!/usr/bin/env python3
"""Failure traces -> skill patches — the loop contract's stop signal, wired to something.

WHAT WAS BEING THROWN AWAY.  `runtime/prompts/_loop-contract.md` already detects the exact signal
the self-improving-agent literature is built on:

    "No progress: the same step fails the same way twice. Two identical failures = stop."

That is a labelled failure trace, generated by ~20 loops, and today it dies as a sentence inside a
dated artifact nobody re-reads. The path from "a loop failed the same way twice" to "the skill or
prompt that told it to do that got edited" runs entirely through the Founder noticing. SkillOpt / EvoSkills
/ MetaSkill-Evolve all close this with the same pipeline — analyze, propose, evolve, keyed off
failure traces. This is that pipeline **with the human on the commit**.

THE FLOW
    loop hits an anti-spin stop  ->  --record  (structured row, names the file in force)
    weekly (Kolby, eval-review)  ->  --propose (clusters recurrences into patch candidates)
    the Founder                         ->  edits the file, commits, --resolve <cluster> --commit <sha>

FOUR HONESTY RULES (tests in runtime/test_agentops.py):

1. **One occurrence is not a pattern.**  Below MIN_RECURRENCE a cluster is `watching`, never
   proposed. Same logic as the autonomy streak rule: one green run is luck, a streak is signal —
   inverted for failures.
2. **It NEVER applies a patch.**  An agent rewriting its own instructions from its own failure
   record is the risk surface in this whole design. The human commit is the control, not ceremony.
   There is deliberately no `--apply`.
3. **A proposal with no identifiable target says so.**  `target: unknown` is a valid, reported
   state. A patch proposal that can't name the file to edit is a complaint, and it is labelled a
   complaint rather than dressed as an action.
4. **Nothing is deleted.**  Append-only; a cluster is closed by a `resolved` event citing the
   commit that closed it, and the original traces stay on disk forever.

CLI
  python3 runtime/failure_traces.py --record --loop content --stop no-progress \\
      --step "fetch brand rules" --detail "..." --target .claude/skills/visual-brand-qa/SKILL.md
  python3 runtime/failure_traces.py --propose            # the weekly read (Kolby)
  python3 runtime/failure_traces.py --resolve <key> --commit <sha> --note "..."
"""
import os, re, sys, json, argparse, datetime

CODE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("YOURCO_DATA_ROOT") or os.path.dirname(CODE)
sys.path.insert(0, CODE)
from ledger import Ledger  # noqa: E402
import run_journal  # noqa: E402

STORE = "loops/_agentops/failures.jsonl"

# The four stops the loop contract already defines. A trace must name one of them — a free-text
# failure taxonomy is a taxonomy nobody can count.
STOPS = ("no-progress", "flip-flop", "missing-input", "budget")

MIN_RECURRENCE = 2     # rule 1 — below this it is `watching`, not a proposal
WINDOW_DAYS = 60       # clustering window; older traces stay on disk but stop driving proposals


def _key(loop, stop, step):
    """Cluster key. The step is normalized so 'fetch brand rules (attempt 2)' and
    'Fetch brand rules' land in one cluster instead of looking like two problems."""
    norm = re.sub(r"[^a-z0-9 ]+", " ", (step or "").lower())
    norm = re.sub(r"\b(attempt|try|retry|run)\s*\d+\b", "", norm)
    norm = " ".join(sorted(set(w for w in norm.split() if len(w) > 2)))[:80]
    return f"{loop}|{stop}|{norm}"


def record(loop, stop, step, detail="", target=None, artifact=None):
    if stop not in STOPS:
        raise ValueError(f"unknown stop '{stop}' — one of {', '.join(STOPS)} (loop contract)")
    return Ledger(STORE).append(
        "trace", loop=loop, agent=run_journal.agent_for(loop), stop=stop, step=step,
        detail=detail, target=target, artifact=artifact, cluster=_key(loop, stop, step))


def resolve(cluster, commit, note=""):
    return Ledger(STORE).append("resolved", cluster=cluster, commit=commit, note=note)


def clusters(days=WINDOW_DAYS, today=None):
    today = today or datetime.date.today()
    since = (today - datetime.timedelta(days=days)).isoformat()
    raw = Ledger(STORE).project()
    resolved = {}
    for e in raw["events"]:
        if e.get("kind") == "resolved":
            resolved[e.get("cluster")] = e
    out = {}
    for e in raw["events"]:
        if e.get("kind") != "trace" or (e.get("ts") or "")[:10] < since:
            continue
        c = out.setdefault(e["cluster"], {
            "cluster": e["cluster"], "loop": e.get("loop"), "agent": e.get("agent"),
            "stop": e.get("stop"), "steps": set(), "targets": set(), "dates": [],
            "details": [], "artifacts": set()})
        c["steps"].add(e.get("step") or "")
        if e.get("target"):
            c["targets"].add(e["target"])
        if e.get("artifact"):
            c["artifacts"].add(e["artifact"])
        c["dates"].append((e.get("ts") or "")[:10])
        if e.get("detail"):
            c["details"].append(e["detail"])
    rows = []
    for c in out.values():
        r = resolved.get(c["cluster"])
        n = len(c["dates"])
        # Rule 3: no target -> a complaint, and it is labelled one.
        tgt = sorted(c["targets"])
        rows.append({
            "cluster": c["cluster"], "loop": c["loop"], "agent": c["agent"], "stop": c["stop"],
            "occurrences": n, "first": min(c["dates"]), "last": max(c["dates"]),
            "steps": sorted(c["steps"]), "targets": tgt,
            "details": c["details"][-3:], "artifacts": sorted(c["artifacts"])[-3:],
            "resolved": bool(r), "resolved_commit": (r or {}).get("commit"),
            "state": ("resolved" if r else
                      "watching" if n < MIN_RECURRENCE else
                      "patch-candidate" if tgt else "unattributed"),
            "target_note": None if tgt else
                ("No file was named when these traces were recorded, so there is nothing to patch. "
                 "This is a complaint, not an action — record --target next time the stop fires."),
        })
    rows.sort(key=lambda r: (-r["occurrences"], r["last"]), reverse=False)
    rows.sort(key=lambda r: -r["occurrences"])
    return {"clusters": rows, "window_days": days, "bad_lines": raw["bad"],
            "store_exists": raw["exists"],
            "counts": {s: sum(1 for r in rows if r["state"] == s)
                       for s in ("patch-candidate", "unattributed", "watching", "resolved")}}


def proposals(days=WINDOW_DAYS, today=None):
    """The weekly read. Emits a PROPOSAL per patch candidate — never an edit (rule 2)."""
    c = clusters(days, today)
    props = []
    for r in c["clusters"]:
        if r["state"] != "patch-candidate":
            continue
        props.append({
            "target": r["targets"][0] if len(r["targets"]) == 1 else r["targets"],
            "loop": r["loop"], "agent": r["agent"], "stop": r["stop"],
            "occurrences": r["occurrences"], "window": f"{r['first']} → {r['last']}",
            "observed": r["steps"],
            "evidence": r["details"],
            "artifacts": r["artifacts"],
            "proposal": (f"{r['occurrences']} runs of `{r['loop']}` stopped on `{r['stop']}` at the "
                         f"same step between {r['first']} and {r['last']}. The instruction in force "
                         f"is `{r['targets'][0] if len(r['targets']) == 1 else ', '.join(r['targets'])}`. "
                         f"Propose an edit to that file so the step either succeeds or is not "
                         f"attempted — the recurrence is evidence the instruction, not the run, is wrong."),
            "cluster": r["cluster"],
            "applies_itself": False,
            "note": "Kolby reviews at eval-review; the Founder edits and commits; then --resolve this cluster.",
        })
    return {**c, "proposals": props}


def main():
    ap = argparse.ArgumentParser(description="Failure traces -> proposed skill/prompt patches.")
    ap.add_argument("--record", action="store_true")
    ap.add_argument("--loop"); ap.add_argument("--stop", choices=STOPS)
    ap.add_argument("--step", default=""); ap.add_argument("--detail", default="")
    ap.add_argument("--target", help="the skill/prompt file that was in force")
    ap.add_argument("--artifact", help="the run artifact that carries the stop")
    ap.add_argument("--propose", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--resolve", metavar="CLUSTER"); ap.add_argument("--commit", default="")
    ap.add_argument("--note", default="")
    ap.add_argument("--days", type=int, default=WINDOW_DAYS)
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    if a.record:
        if not (a.loop and a.stop):
            ap.error("--record needs --loop and --stop")
        ev = record(a.loop, a.stop, a.step, a.detail, a.target, a.artifact)
        print(f"trace seq={ev['seq']} {a.loop} [{a.stop}] cluster={ev['cluster']}")
        return
    if a.resolve:
        if not a.commit:
            ap.error("--resolve needs --commit (the change that closed it)")
        ev = resolve(a.resolve, a.commit, a.note)
        print(f"resolved seq={ev['seq']} {a.resolve} @ {a.commit}")
        return

    data = proposals(a.days) if a.propose else clusters(a.days)
    if a.json:
        print(json.dumps(data, indent=2, default=list)); return
    if not data["store_exists"]:
        print("  No failure traces recorded yet. Loops write here when they hit an anti-spin stop\n"
              "  (see runtime/prompts/_loop-contract.md). An empty store means either no stops have\n"
              "  fired since wiring, or the wiring is not being honoured — the eval-review checks which.")
        return
    if a.propose:
        print(f"Patch proposals — {len(data['proposals'])} candidate(s), {data['window_days']}d window\n")
        for p in data["proposals"]:
            print(f"  TARGET: {p['target']}")
            print(f"    {p['proposal']}")
            for e in p["evidence"]:
                print(f"    evidence: {e[:140]}")
            print(f"    {p['note']}\n")
        if not data["proposals"]:
            print("  None. " + "  ".join(f"{k}={v}" for k, v in data["counts"].items() if v))
        return
    for r in data["clusters"]:
        print(f"  [{r['state']:<15}] {r['loop']}/{r['stop']}  x{r['occurrences']}  "
              f"({r['first']}→{r['last']})")
        print(f"        target: {', '.join(r['targets']) or 'UNKNOWN'}")
        if r["target_note"]:
            print(f"        {r['target_note']}")
    print("\n  " + "  ".join(f"{k}={v}" for k, v in data["counts"].items() if v))


if __name__ == "__main__":
    main()
