window.ADDRESS = {
  "address": {
    "matched": "1 E INDEPENDENT DR, JACKSONVILLE, FL, 32202",
    "lat": 30.325113737704,
    "lon": -81.657528819577,
    "county": "Duval"
  },
  "radius": 15,
  "best": {
    "date": "2025-07-29",
    "hazard": "wind",
    "value": 70.0,
    "county": "Duval",
    "city": "1 SE Jacksonville",
    "lat": 30.32,
    "lon": -81.64,
    "reporter": "Mesonet",
    "qualifier": "M",
    "remark": "Delayed report from Tuesday afternoon - the WeatherSTEM station at WJCT in downtown Jacksonville recorded a peak wind gust of 70 mph as thunderstorms moved through the area.",
    "dist": 1.1,
    "days_ago": 337,
    "claim_days_left": 28,
    "severity": 56.0,
    "hazard_str": "70 mph wind"
  },
  "alternates": [
    {
      "date": "2026-03-16",
      "hazard": "wind",
      "value": 68.0,
      "county": "Duval",
      "city": "1 ENE Fort Caroline",
      "lat": 30.39,
      "lon": -81.48,
      "reporter": "Mesonet",
      "qualifier": "M",
      "remark": "Mesonet WXFlow station XJAK Jacksonville measured a gust of 68 mph.",
      "dist": 11.5,
      "days_ago": 107,
      "claim_days_left": 258,
      "severity": 54.4,
      "hazard_str": "68 mph wind"
    },
    {
      "date": "2026-03-16",
      "hazard": "wind",
      "value": 61.0,
      "county": "Duval",
      "city": "4 NE Orange Park",
      "lat": 30.22,
      "lon": -81.67,
      "reporter": "AWOS",
      "qualifier": "M",
      "remark": "AWOS station KNIP Jacksonville Nas measured a peak wind speed of 61 mph.",
      "dist": 7.3,
      "days_ago": 107,
      "claim_days_left": 258,
      "severity": 48.8,
      "hazard_str": "61 mph wind"
    },
    {
      "date": "2026-03-16",
      "hazard": "wind",
      "value": 61.0,
      "county": "Duval",
      "city": "4 NE Orange Park",
      "lat": 30.22,
      "lon": -81.67,
      "reporter": "AWOS",
      "qualifier": "M",
      "remark": "Corrects previous time for tstm wnd gst report from 4 NE Orange Park. AWOS station KNIP Jacksonville Nas measured another gust of 61 mph.",
      "dist": 7.3,
      "days_ago": 107,
      "claim_days_left": 258,
      "severity": 48.8,
      "hazard_str": "61 mph wind"
    },
    {
      "date": "2026-03-16",
      "hazard": "wind",
      "value": 61.0,
      "county": "Duval",
      "city": "4 NE Orange Park",
      "lat": 30.22,
      "lon": -81.67,
      "reporter": "AWOS",
      "qualifier": "M",
      "remark": "AWOS station KNIP Jacksonville Nas measured another gust of 61 mph.",
      "dist": 7.3,
      "days_ago": 107,
      "claim_days_left": 258,
      "severity": 48.8,
      "hazard_str": "61 mph wind"
    }
  ],
  "count": 199
};
